# Generated by Django 4.0.5 on 2022-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pubinno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('adress', models.TextField()),
                ('openning_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
        ),
    ]
